apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - uses: https://github.com/cloudbees-io/checkout@v1
      - name: build code
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          export GOPATH=$HOME/go
          export PATH=$PATH:$GOPATH/bin
          go version
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o demo-app
      - name: Register an artifact with the platform
        uses: cloudbees-io/register-build-artifact@v1
        id: register
        with:
          name: myApp
          url: docker.io/myapp/myimg:1.0.0
          version: ${{ $(date '+%Y%m%d%H%M%S') }}