apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: expression-injection.yml

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo ${{ cloudbees.scm.ref }}
